"""empty message

Revision ID: ac0271927bc
Revises: 17b9863c3c31
Create Date: 2015-01-15 11:46:34.749000

"""

# revision identifiers, used by Alembic.
revision = 'ac0271927bc'
down_revision = '17b9863c3c31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_foreign_key('fk_group_creator_id', 'group', 'user', ['creator_id'], ['id'])
    #op.create_foreign_key('fk_institution_creator_id', 'institution', 'user', ['administrator_id'], ['id'])
    op.drop_column('user', 'view_system_only')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('view_system_only', sa.BOOLEAN(), nullable=True))
    #op.drop_constraint('fk_institution_creator_id', 'institution', type_='foreignkey')
    #op.drop_constraint('fk_group_creator_id', 'group', type_='foreignkey')
    ### end Alembic commands ###
